# -*- coding: utf-8 -*-
"""Data Visualization.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kTeXXvxkdskRwC-ZaHDA3Aqd_rCbDXIV
"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import pandas as pd
# %matplotlib inline

from google.colab import drive
drive.mount('/content/gdrive')
root_path = 'gdrive/My Drive/'

df1 = pd.read_csv('gdrive/My Drive/df1',index_col=0)
df2 = pd.read_csv('gdrive/My Drive/df2')

df1

df1['A'].hist()

"""plt.style.use()"""

import matplotlib.pyplot as plt
plt.style.use('ggplot')
df1['A'].hist()

plt.style.use('bmh')
df1['A'].hist()

plt.style.use('dark_background')
df1['A'].hist()

"""plot types
AREA plot
"""

df2.plot.area(alpha=0.4)

df2.plot.area()

df2.plot.area(alpha=0.2)

"""BARSPLOT"""

df2.head()

df2.plot.bar()

df2.plot.bar(stacked=True)

"""HISTOGRAMS"""

df1['A'].plot.hist(bins=50)

"""LINE PLOTS

importing packages
"""

# Commented out IPython magic to ensure Python compatibility.

import seaborn as sns
import matplotlib.pyplot as plt
# %matplotlib inline

data = sns.load_dataset("iris")

sns.lineplot(x="sepal_length",y="sepal_width",data=data)

"""Scatter plots"""

df1.plot.scatter(x='A',y='B')

df1.plot.scatter(x='A',y='B',c='C',cmap='coolwarm')

df1.plot.scatter(x='A',y='B',s=df1['C']*200)

import time 
timestamp = time.time()
print(timestamp)