# -*- coding: utf-8 -*-
"""data preprocessing.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sft34Z3KCjIUIimqh6ZPmAOrehbc6Gtm
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

from google.colab import drive
drive.mount('/content/gdrive')
root_path = 'gdrive/My Drive/'

dataset=pd.read_csv('gdrive/My Drive/data.csv')

dataset

print(dataset['age'].mean())

dataset['age']=dataset['age'].fillna(dataset['age'].mean())

dataset

print(dataset['salary'].mean())

dataset['salary']=dataset['salary'].fillna(dataset['salary'].mean())

dataset

X=dataset.iloc[:, :-1].values
Y=dataset.iloc[:, -1].values

X

Y

Z=dataset.iloc[:3, -1].values

Z

Z=dataset.iloc[-1, :].values

Z

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct= ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0])],remainder='passthrough')
X=np.array(ct.fit_transform(X))

X

from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
Y=le.fit_transform(Y)

Y

from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X,Y,test_size=0.2)

X_train

X_test

Y_train

Y_test

import time 
timestamp = time.time()
print(timestamp)

"""1000 companies"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

from google.colab import drive

drive.mount('/content/gdrive')

root_path='gdrive/My Drive'

companies=pd.read_csv('gdrive/My Drive/1000_Companies.csv')

companies

x=dataset.iloc[:,:-1].values

x

y=dataset.iloc[:,4].values

y

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct=ColumnTransformer(transformers=[("encoder", OneHotEncoder(), [3])], remainder="passthrough")
x=np.array(ct.fit_transform(x))

x

from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
y=le.fit_transform(y)

y

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 1)

x_train

x_test

y_train

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2,random_state=0)

x_train

companies.head()

companies.tail()

companies.shape

companies.describe()

companies.columns

companies.nunique()

companies['State'].unique()

companies['Profit'].unique()

companies.isnull().sum()

data=companies.drop(['State','Marketing Spend'],axis=1)

data.head()

sns.heatmap(companies.corr())

import time 
timestamp = time.time()
print(timestamp)

"""Iris dataset"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

from google.colab import drive

drive.mount('/content/gdrive')

root_path='gdrive/My Drive'

dataset=pd.read_csv('gdrive/My Drive/Iris.csv')

dataset

dataset.head()

dataset.tail()

dataset.shape

dataset.describe()

dataset.columns

dataset.nunique()

dataset['SepalWidthCm'].unique()

dataset['Species'].unique()

dataset.isnull().sum()

data=dataset.drop(['SepalLengthCm','SepalWidthCm'],axis=1)

data.head()

sns.heatmap(dataset.corr())

dataset.info()

"""splitting"""

x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

x

y

from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
y=le.fit_transform(y)

y

import time 
timestamp = time.time()
print(timestamp)