# -*- coding: utf-8 -*-
"""python fundamental.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Z9e3LnTqDyH_nS6t6NvyUApco6ZngRIf
"""

1+1

1/2

1*3

2**4

4%2

5%2

(2+3) * (5+5)

"""variable assignment"""

name_of_var = 2

x = 2
y=3
xy=(x + y)

"""strings"""

'single quotes'

"double quotes"

" wrap lot's of other quotes "

"""printing"""

x = 'hello'

x

print(x)

num = 12
name = 'sam'

print('my number is:{one},and my name is:{two}'.format(one=num,two=num))

print('my name is:{},and my name is:{}'.format(num,name))

color = 'blue'
number = 1234567
print('my favourite color is:{},and my nubmer is:{}'.format(color,number))

num = 20
name = "vaishali"
print ("My number is {}, and {}".format(num,name))

num = 20
name = "vaishali"
print ("My number is {one}, and {two}".format(one=num,two=name))

"""lists"""

[1,2,3]

['hi',1,[1.2]]

my_list = ['a','b','c']

my_list

my_list.append('d')

my_list

my_list[0]

my_list[1]

my_list[1:]

my_list[:1]

my_list[:3]

my_list[0] = 'New'

my_list

"""comparison operators"""

1>2

1<2

1>=1

1<=4

1==1

'hi' == 'bye'

"""Logic operator(and/or)"""

(1>2) and (2<3)

(1>2) or (2<3)

(1==2) or (2==3) or (4==4)

"""if,elif,else statements"""

if 1<2:
  print('Yep!')

if 1>2:
  print('yep!')

if 2>1:
  print('yep!')

if 1<2:
  print('first')
else:
  print('last')

if 1 == 2:
  print('first')
elif 3 == 3:
  print('middle')
else:
  print('last')

if 2>1:
  print('first')
elif 2==2:
  print('middle')
elif 2>1:
  print('third')  
else:
  print('last')

"""for loops(important)"""

seq = [1,2,3,4,5]
for item in seq:
  print(item)

for item in seq:
  print('yep')

my_list = [1,2,3,4,5,"hello"]
my_list[0]
my_list.append("vini")
print(my_list)

new = [1,2,3,4,"happy"]
print(new)
new[2] = "hello"
new

"happy"!="sad"

if 50<200:
    print("greater")
else:
    print("smaller")

seq=[1,2,44,5]
for item in seq:
  print(item)
  for X in seq:
    print("bye")

import time 
timestamp = time.time()
print(timestamp)